development:
  adapter: postgresgl
  encoding: unicode
  database: todo_app_back_end_development
  
test:
  adapter: postgresgl
  encoding: unicode
  database: todo_app_back_end_test
  
production:
  adapter: postgresgl
  encoding: unicode
  databse: todo_app_back_end_production
